README.md
build.sbt
circle.yml
project/build.properties
project/plugins.sbt

- Builds on [Circle CI](https://circleci.com/gh/guardian/identity-frontend)
- Packages `riffRaffArtifact` - does not upload to riffraff buckets yet

Build on Circle CI

---

.editorconfig
.gitignore

Minor project config

---

app/com/gu/identity/frontend/controllers/Application.scala
app/com/gu/identity/frontend/controllers/SigninAction.scala
app/com/gu/identity/frontend/services/package.scala
app/com/gu/identity/frontend/views/ViewRenderer.scala
app/com/gu/identity/frontend/views/models/SignInViewModel.scala
conf/routes
public/components/signin/_signin.css
public/signin-page.hbs
test/com/gu/identity/frontend/controllers/SigninActionSpec.scala

Display errors

---

app/com/gu/identity/frontend/controllers/SigninAction.scala
app/com/gu/identity/frontend/models/TrackingData.scala
app/com/gu/identity/frontend/services/IdentityService.scala
app/com/gu/identity/frontend/utils/RemoteAddress.scala
app/com/gu/identity/service/client/ApiRequests.scala
app/com/gu/identity/service/client/IdentityClient.scala
test/com/gu/identity/frontend/controllers/SigninActionSpec.scala
test/com/gu/identity/frontend/utils/RemoteAddressSpec.scala
test/com/gu/identity/service/client/AuthenticateCookiesRequestSpec.scala

Tracking Data and client ip extraction copied from frontend

Add tracking data to id api requests.

---

package.json
public/components/analytics/analytics.js
public/components/analytics/mvt.js
public/components/analytics/omniture-adapter.js
public/components/analytics/ophan.js

- Extracts user IDs from cookies as per original logic in frontend
- Record mvt results in Omniture and Ophan as per original logic in frontend

Record MVT results in Omniture and Ophan

---

.prout.json
app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala
app/com/gu/identity/frontend/controllers/Manifest.scala
build.sbt
conf/routes
project/plugins.sbt

@jamespamplin 
* Added `/management/manifest` endpoint which Prout checks for commit SHA.
* Overdue deployment to CODE is set to 15 min limit
* Overdue deployment to PROD is set to 1 hour limit (since deploy to PROD is a manual process)
Tested on a [forked repository](https://github.com/mario-galic/identity-frontend/pull/2)

Enable Prout

---

app/com/gu/identity/frontend/views/models/SignInViewModel.scala
test/com/gu/identity/frontend/views/models/UrlBuilder$Test.scala

Fixes broken links on Prod for forgot password and sign up.

Removed trailing slash from links

---

.prout.json

Fix PROD endpoint in Prout config

---

cloudformation/identity-frontend.template

Latest AMI has identity-functions and security updates installed.

Updated to use latest AMI

---

app/com/gu/identity/frontend/controllers/Application.scala
app/com/gu/identity/frontend/controllers/SigninAction.scala
app/com/gu/identity/frontend/views/ViewRenderer.scala
app/com/gu/identity/frontend/views/models/SignInViewModel.scala
conf/routes
public/components/browser/browser.js
public/components/browser/dom-element.js
public/components/browser/storage.js
public/components/signin/signin.js
public/main.js
public/signin-page.hbs
test/com/gu/identity/frontend/controllers/SigninActionSpec.scala

Remembers the user's email address in browser `sessionStorage` instead of using a URL parameter.

Remember email in sessionStorage

---

CONTRIBUTING.md
LICENSE
README.md

- License specified
- Minor updates on local dependencies and how to run locally
- [`CONTRIBUTING.md`](https://github.com/guardian/identity-frontend/blob/docs-update/CONTRIBUTING.md) - including style guidelines, structure, and how front-end sources are written.

Updates to Documentation

---

functional-tests/build.sbt
functional-tests/src/test/scala/SigninSpec.scala
functional-tests/src/test/scala/pages/FacebookAuthDialog.scala
functional-tests/src/test/scala/pages/FacebookLogin.scala
functional-tests/src/test/scala/pages/FacebookProvidedInfoDialog.scala
functional-tests/src/test/scala/pages/Homepage.scala
functional-tests/src/test/scala/pages/Register.scala
functional-tests/src/test/scala/pages/Signin.scala

@jamespamplin 
[Example screencast](https://saucelabs.com/tests/2d7c47165fce46f497a17ff48d3c2123)
Added test scenario:
"Users attempt to register with Facebook without granting email permissions."

Add Facebook email permission test

---

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala
app/com/gu/identity/frontend/filters/Filters.scala
app/com/gu/identity/frontend/filters/LogRequestsFilter.scala
conf/logback.xml

Update logger to log all access requests made to identity-frontend

Add access logs.

---

functional-tests/src/test/scala/pages/Signin.scala

@jamespamplin 
Update of functional tests due to https://github.com/guardian/identity-frontend/pull/63

Update social signin IDs

---

functional-tests/src/test/scala/pages/Register.scala
functional-tests/src/test/scala/pages/RegisterConfirm.scala

Update register page for RegisterV2

---

public/signin-page-b.hbs
public/signin-page.hbs

Use correct field names for remember me on sign in.

Fix remember me functionality on Sign in

---

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala
app/com/gu/identity/frontend/controllers/CSPViolationReporter.scala
app/com/gu/identity/frontend/views/models/ContentSecurityPolicy.scala
conf/routes
test/com/gu/identity/frontend/views/models/ContentSecurityPolicySpec.scala

When The CSP is violated a POST request is made to csp/report and the violation is logged

Report csp violations

---

test/com/gu/identity/frontend/views/models/ContentSecurityPolicySpec.scala

- Fixed broken tests for CSP due to changing the route for the report in
#81

Fixed broken CSP test due to #81

---

app/com/gu/identity/frontend/controllers/CSPViolationReporter.scala

Minor alteration to log message.

Update log message for csp violations.

---

conf/CODE.conf
conf/DEV.conf
conf/PROD.conf

Removing re-captcha due to issues mentioned in the PEN test report.

Disable re-captcha

---

public/_layout.css
public/components/_typography.css
public/components/form-foundations/_form_foundations.css
public/components/membership/_membership.css
public/register-page.hbs

- Padding below standfirst
- "or" text uses Guardian Egyptian Web font
- Removed glow on hover of form CTAs

Style tweaks as requested by UXD

---

functional-tests/build.sbt
functional-tests/src/test/resources/application.conf
functional-tests/src/test/scala/SigninSpec.scala
functional-tests/src/test/scala/pages/ResetPassword.scala
functional-tests/src/test/scala/util/Config.scala
functional-tests/src/test/scala/util/Driver.scala
functional-tests/src/test/scala/util/Mail.scala

@emma-p 
Uses Java Mail API to access Gmail inbox via IMAP.
[Screencast](https://saucelabs.com/tests/0f81eb07657a4b8e98c08cff965a89c3)

Add reset password test

---

conf/application.conf

See https://www.playframework.com/security/vulnerability/20160304-CsrfBypass

Add contentType config to CSRF

---

functional-tests/src/test/scala/SigninSpec.scala
functional-tests/src/test/scala/pages/ResetPassword.scala

Update reset ID attributes

---

public/components/form-foundations/_form_foundations.css
public/components/oauth-cta/_oauth-cta.css

Make border-radius 18px on fields / buttons

---

app/com/gu/identity/frontend/mvt/MultiVariantTests.scala

Add control to results for easy segmentation of users.

Added control and updated audience

---

app/com/gu/identity/frontend/filters/LogRequestsFilter.scala

Log full Request URI (including query) to aid debugging

Log full Request URI in Access log

---

app/com/gu/identity/frontend/filters/LogRequestsFilter.scala

`System.nanoTime` should be used to measure time elapsed [see javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#nanoTime).

Use nano time to measure time elapsed

---

public/components/analytics/omniture-adapter.js

Removes previously disabled code and unreachable code as determined as unnecessary for Omniture tracking.

Cleanup Omniture Adapter

---

app/com/gu/identity/frontend/errors/AppException.scala
app/com/gu/identity/frontend/errors/ErrorID.scala
app/com/gu/identity/frontend/services/IdentityServiceRequestHandler.scala
app/com/gu/identity/frontend/views/models/ErrorViewModel.scala
app/com/gu/identity/service/client/Errors.scala

Handle fbError and Rate limiting errors from the identity api.

Handle Social and Rate-limiting errors

---

conf/DEV.conf
functional-tests/src/test/resources/application.conf
functional-tests/src/test/scala/SigninSpec.scala
functional-tests/src/test/scala/pages/Homepage.scala
functional-tests/src/test/scala/pages/Signin.scala
functional-tests/src/test/scala/util/Config.scala

@emma-p
Local DEV frontend targets CODE backend.

Enable tests in DEV and CODE environments

---

app/com/gu/identity/frontend/models/text/RegisterConfirmationText.scala
conf/messages.en
public/_layout.css
public/components/register-confirmation/_register-confirmation.css
public/register-confirmation-page.hbs

New design implemented. Haven't done the name part for now.
See screenshot:

#1399 Web We Want: Welcome new users to the community

---

app/com/gu/identity/frontend/models/text/OAuthText.scala
app/com/gu/identity/frontend/mvt/MultiVariantTests.scala
app/com/gu/identity/frontend/views/models/OAuthViewModel.scala
conf/messages.en
public/components/oauth-cta/_oauth-cta.css
public/components/oauth-cta/_oauth-cta.hbs

Removed test and defaulted back to control as result was not conclusive.

Remove permission a/b test

---

app/com/gu/identity/frontend/views/models/ErrorViewModel.scala

. Change copy from "20" to "72" characters

Update Password copy

---

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala
app/com/gu/identity/frontend/controllers/DigitalAssetLinks.scala
app/com/gu/identity/frontend/controllers/SigninAction.scala
app/com/gu/identity/frontend/errors/RedirectOnError.scala
app/com/gu/identity/frontend/models/DigitalAsset.scala
app/com/gu/identity/frontend/views/models/SignInViewModel.scala
conf/routes
public/components/browser/dom-element.js
public/components/signin-form/_signin-form.hbs
public/components/signin-form/signin-form.js

Implementation of Google Smart Lock.  
[Google Developer Docs](https://developers.google.com/web/updates/2016/04/credential-management-api?hl=en)

Smart lock

---

app/com/gu/identity/frontend/configuration/Configuration.scala
app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala
app/com/gu/identity/frontend/logging/SentryLogging.scala
app/com/gu/identity/frontend/views/models/LayoutViewModel.scala
build.sbt
project/plugins.sbt

Add Scala Sentry client

---

functional-tests/build.sbt
functional-tests/src/test/scala/pages/FacebookProvidedInfoDialog.scala

Fix Facebook email permission test

---

package.json

@markjamesbutler 
http://blog.getsentry.com/2016/05/04/breadcrumbs.html

Enable Sentry JS breadcrumbs

---

app/com/gu/identity/frontend/controllers/RegisterAction.scala
app/com/gu/identity/frontend/services/IdentityService.scala

@nlindblad 
[Trello ticket](https://trello.com/c/C5jQqvVz/8-user-could-not-be-logged-in-after-registering)

Add register diagnostic context

---

app/com/gu/identity/frontend/controllers/RegisterAction.scala
app/com/gu/identity/frontend/controllers/SigninAction.scala
app/com/gu/identity/frontend/logging/MetricsActor.scala
app/com/gu/identity/frontend/logging/SuccessfulActionCloudwatchLogging.scala
public/components/reset-password/reset-password.js
public/components/signin-form/signin-form.js

Update to smart lock sign-in mechanism to remove infinite loop on password reset.  Prior to this PR the smart lock JS would continually attempt to execute sign-in if the credientials were incorrect.  I.e. The user has changed their password.
Additionally, specific cloud watch logging has been added for smart lock sign-ins.

Smart lock password reset fix

---

public/components/signin-form/signin-form.js

I've obviously been doing too much Scala.

Add missing semi colons

---

app/com/gu/identity/frontend/controllers/ThirdPartyTsAndCs.scala
app/com/gu/identity/frontend/models/text/ThirdPartyTsAndCsText.scala
app/com/gu/identity/frontend/views/ViewRenderer.scala
app/com/gu/identity/frontend/views/models/TsAndCsViewModel.scala
conf/messages.en
public/components/third-party-ts-and-cs/_third-party-ts-and-cs.css
public/third-party-ts-and-cs-page.hbs

Improve copy on agreement pages

---

functional-tests/src/test/scala/pages/FacebookAuthDialog.scala

Lookup editInfoLink by id

---

functional-tests/build.sbt
functional-tests/src/test/scala/pages/FacebookAuthDialog.scala
functional-tests/src/test/scala/pages/FacebookProvidedInfoDialog.scala
functional-tests/src/test/scala/util/Browser.scala

@nlindblad 
Using newly introduced [logical operator OR](https://github.com/SeleniumHQ/selenium/commit/6d8e8197e13396bebee870791785b709caa32ff3#diff-8c2ba6b53e16c4f466493a012f3113b7R1415) in Selenium 2.53 to handle Facebook performing A/B testing.

Handle Facebook performing A/B testing

---

functional-tests/build.sbt
functional-tests/src/test/scala/SigninSpec.scala
functional-tests/src/test/scala/util/Driver.scala

Remove Facebook email permission test

---

app/com/gu/identity/service/client/request/RegisterApiRequest.scala

This seems to break on my machine but not CI which is weird.

Removing unresolved export to fix build

---

app/com/gu/identity/frontend/configuration/Configuration.scala
app/com/gu/identity/frontend/views/models/LayoutViewModel.scala
conf/CODE.conf
conf/DEV.conf
conf/PROD.conf
public/components/analytics/analytics.js
public/components/analytics/ga.js
public/components/configuration/configuration.js
public/components/sentry/sentry.js

Add page view tracking.  Further PR's will enhance the tracking.

GA Page view tracking

---

app/com/gu/identity/frontend/models/Text.scala
app/com/gu/identity/frontend/views/ViewRenderer.scala
conf/messages.en
public/components/membership/_membership.css
public/components/signin-form-mem/_signin-form-mem.hbs
public/signin-page-membership.hbs
public/signin-page.hbs

This PR implements the new design for membership sign in. 
Screen Shot of the new design:

New sign in page for membership

---

public/components/membership/_membership.css
public/components/register-form-mem/_register-form-mem.hbs

In the new sign up design, the submit button is not working. This PR, fix that issue.
@SiAdcock please review this change.

Bug fix, the submit button is working in the new sign up design

---

app/com/gu/identity/frontend/models/text/RegisterText.scala
app/com/gu/identity/frontend/views/models/RegisterViewModel.scala
conf/messages.en

This PR rollback the changes made by the PR: https://github.com/guardian/identity-frontend/pull/185/files
Please @markjamesbutler see this PR.

Reverted the chances made in the PR: #185

---

project/build.properties

Use sbt v0.13.13 for faster compile times!

---

conf/routes
public/robots.txt

@markjamesbutler @stephanfowler @jfsoul

Adds robots.txt with Disallow: /user/

---

app/com/gu/identity/frontend/errors/ErrorID.scala
app/com/gu/identity/frontend/errors/RegisterAppException.scala
app/com/gu/identity/frontend/views/models/ErrorViewModel.scala
app/com/gu/identity/frontend/views/models/RegisterErrorViewModel.scala
app/com/gu/identity/service/client/Errors.scala

Related PR: https://github.com/guardian/identity/pull/635
@andrewfindlay

Handle reserved email error

---

README.md

Added info to docs as it was missing.

Docs: Using local idapi

---

README.md
conf/DEV.conf
functional-tests/src/test/scala/util/Config.scala

Related PR: https://github.com/guardian/identity-platform/pull/170

Use profile.thegulocal.com instead profile-origin

---

cloudformation/identity-frontend.yaml
riff-raff.yaml

- Riff-raff dependancy now relies on identity-base recipe
- Set up userData for using amigo

Update cfn to use amigo

---

cloudformation/identity-frontend.yaml

Silencing those annoying CODE alarm emails...

Remove notification alarms from CODE

---

app/com/gu/identity/frontend/models/text/RegisterText.scala
app/com/gu/identity/frontend/request/RegisterActionRequestBody.scala
app/com/gu/identity/frontend/services/IdentityServiceRequestHandler.scala
build.sbt
public/components/register-form/_form-fields.hbs
test/com/gu/identity/frontend/services/IdentityServiceRequestHandlerSpec.scala

Related PR: https://github.com/guardian/identity/pull/720

Use GDPR consent by product model

---

build.sbt

- Bump Identity library to current version

bump id version number

---

public/_colors.css
public/_layout.css
public/components/fonts/_fonts.css
public/components/form-foundations/_form_foundations.css
public/components/header/_header.css
public/components/icon/arrow-inline.hbs
public/components/oauth-cta/_oauth-cta.css
public/components/register-form-mem/_register-form-mem.hbs
public/components/register-form/_register-form.css
public/components/register-form/_register-form.hbs
public/components/reset-password/_reset-password.css
public/components/signin-form-mem/_signin-form-mem.hbs
public/components/signin-form/_signin-form.css
public/components/signin-form/_signin-form.hbs
public/components/terms/_terms.hbs
public/register-confirmation-page.hbs
public/register-page.hbs
public/reset-password-page.hbs
public/signin-page.hbs

Snow updates

---

public/_colors.css
public/_layout.css
public/components/_typography.css
public/components/form-foundations/_form_foundations.css
public/components/header/_header.css
public/components/oauth-cta/_oauth-cta.css

Aligns all the changes closer with the existing page to make it less work for design to okay it

[minor] snow css cleanup

---

app/com/gu/identity/frontend/views/models/ErrorViewModel.scala
conf/messages.en

Change wording for reset password to be inclusive of guest accounts

Update reset password wording

---

public/components/form-foundations/_form_foundations.css
public/components/header/_header.css
public/components/oauth-cta/_oauth-cta.css

Sync cta's up with the guidelines, fix header logo going to the left

[trivial] Snowy bugfixes

---

app/com/gu/identity/frontend/models/text/RegisterText.scala
app/com/gu/identity/frontend/views/ViewRenderer.scala
app/com/gu/identity/frontend/views/models/LayoutViewModel.scala
app/com/gu/identity/frontend/views/models/RegisterViewModel.scala
public/main.css

Tweaks the siteskins for the Garnett launch
- Identity is now using the same html but with the custom copy they had
- Jobs has a different standfirst, no logo (for now)

Snowy siteskins

---

public/components/header/_header.css

Fix the header on very old browsers so it renders nicely.

Fix header on old browsers

---

public/components/reset-password/_reset-password.css

God i just love underlines so much

Underline 'contact userhelp', 'sign out' links

---

app/com/gu/identity/frontend/configuration/Configuration.scala

Enable snow

---

app/com/gu/identity/frontend/controllers/ConsentController.scala
app/com/gu/identity/frontend/errors/DeauthenticateAppException.scala
app/com/gu/identity/frontend/errors/ErrorID.scala
app/com/gu/identity/frontend/errors/HttpError.scala
app/com/gu/identity/frontend/models/text/ErrorPageText.scala
app/com/gu/identity/frontend/services/IdentityService.scala
app/com/gu/identity/service/client/Errors.scala
conf/messages.en
public/components/error-page-content/_error-page-content.hbs

- Better messaging on expired token page, not just generic 404
- In future PR will integrate an endpoint in Identity so we can have a "resend link" button on this page.

Better messaging on expired token page

---

public/_colors.css
public/_layout.css
public/components/_typography.css
public/components/fonts/_fonts.css
public/components/oauth-cta/_oauth-cta.css
public/components/terms/_terms.css
public/signin-page.hbs

Move the signup link to the header, from its original location down at the footer

Make [Sign up] link more prominent

---

app/com/gu/identity/frontend/controllers/RepermissionController.scala

Redirect to new /staywithus URL for repermission journey.

redirect to staywithus

---

public/_colors.css
public/components/form-foundations/_form_foundations.css
public/components/form-foundations/tick.svg
public/components/header/_header.css
public/components/header/_header.hbs
public/components/jobs/_jobs.css

Minor tweaks to colours & checkboxes to match /consents

Sync up design with /consents

---

package.json
public/components/_grid.css

- Fixes css columns
- Fixes webpack compiling itself in dev mode

Fix new build tool issues

---

app/com/gu/identity/frontend/views/models/TwoStepSignInViewModel.scala
public/components/form-foundations/_form_foundations.css
public/components/form/_form.css
public/components/form/form-error-wrap.hbs
public/main.css
public/two-step-signin-choices-page.hbs
public/two-step-signin-start-page.hbs

Show errors on two step signin pages

---

public/components/two-step-signin/two-step-signin.js
public/components/two-step-signin/two-step-signin__slide.js
public/js/config.js
public/js/load-components.js
public/main.js

js-enhanced two step sign in

---

public/components/form-foundations/_form_foundations.css
public/components/form/_form.css
public/components/form/form-input.js
public/components/two-step-signin/two-step-signin-email.hbs
public/components/two-step-signin/two-step-signin-existing.hbs
public/components/two-step-signin/two-step-signin.js
public/js/load-components.js

- When loading a new page, automatically put focus on text inputs so as a user you can do email/enter/password/enter and carry on
- Inputs go red in error after unfocusing them for the first time ever, so the first time you type in them they aren't red

Input field improvements

---

public/components/two-step-signin/_helpers.hbs
public/components/two-step-signin/two-step-signin__ga-client-id.js
public/js/load-components.js

They weren't doing this and now they are

Populate gaClientId in 2 step signin forms

---

public/_layout.css
public/components/form/_form.css
public/components/two-step-signin/two-step-signin-new.hbs
public/two-step-signin-start-page.hbs

Fixes a couple of css gripes, plus puts the signup link in the footer so the email field is front and center

Minor design tweaks

---

public/main.js

Load sentry first

---

public/components/form/_form.css
public/components/two-step-signin/two-step-signin-existing.hbs
public/components/two-step-signin/two-step-signin.js
public/components/two-step-signin/two-step-signin__slide.js

Makes the js handing the 2 step sign in more robust, as well as makes it work at all, since it was temporarily disabled during the endpoint testing

Fix javascript in 2 step sign in

---

public/js/config.js

Use flow in config.js

---

app/com/gu/identity/frontend/views/models/LayoutViewModel.scala
public/components/two-step-signin/_two-step-signin.css
public/components/two-step-signin/two-step-signin.js
public/components/two-step-signin/two-step-signin__slide.js

Did a round of browserstacking and solved a nasty animation-related bug + refactored `two-step-signin__slide.js`

Clean up js

---

app/com/gu/identity/frontend/views/models/TwoStepSignInViewModel.scala
public/two-step-signin-choices-page.hbs

Fixes a nasty bug where signin would be absolutely broken (the pink input is only visible for me because i enabled it via the devtools)

Fix email being loaded with extra html bits in 2 step signup

---

conf/messages.en
public/_html.css
public/components/form/_form.css
public/signin-page.hbs

Not a fan of the visual design but it is larger and more prominent
@katyabeer

Larger sign up button

---

public/components/analytics/analytics-in-page-click.js
public/components/analytics/ga.js
public/components/form/form-input.js
public/components/smartlock-trigger/smartlock-trigger.js
public/components/two-step-signin/two-step-signin.js
public/components/two-step-signin/two-step-signin__ga-client-id.js
public/components/two-step-signin/two-step-signin__slide.js
public/js/load-components.js

* Track ajax pv's in GA
* Support `data-link-name` for sending events (to GA but not DL)

Improve GA tracking

---

app/com/gu/identity/frontend/models/Text.scala
app/com/gu/identity/frontend/views/models/LayoutViewModel.scala
public/components/form-error-wrap/index.js
public/components/form/form-error-wrap.hbs
public/components/two-step-signin/two-step-signin.js
public/components/two-step-signin/two-step-signin__slide.js
public/js/config.js
public/js/load-components.js

Report back errors gotten while signing in via js. This PR mostly adds the scaffolding to then report errors to.

Report errors from 2 step sign in JS

---

app/com/gu/identity/frontend/controllers/SigninAction.scala
app/com/gu/identity/frontend/views/models/LayoutViewModel.scala
public/components/two-step-signin/two-step-signin__slide.js
public/js/get-url-errors.js

Sign in (2 step) with a password via javascript too, making the flow neater and more lively.

Password sign in via javascript

---

app/com/gu/identity/frontend/controllers/SigninAction.scala
public/components/form/_form.css

Got late to @rahilb comments but wholeheartedly agree with them. Forgot how bad that side was!

 Password sign in via javascript scala improvements

---

app/com/gu/identity/frontend/controllers/Application.scala
app/com/gu/identity/frontend/models/text/SendSignInLinkSentText.scala
app/com/gu/identity/frontend/models/text/SendSignInLinkText.scala
app/com/gu/identity/frontend/views/ViewRenderer.scala
app/com/gu/identity/frontend/views/models/SendSignInLinkSentViewModel.scala
app/com/gu/identity/frontend/views/models/SendSignInLinkViewModel.scala
conf/messages.en
conf/routes
public/components/form/_form.css
public/send-sign-in-link-sent.hbs
public/send-sign-in-link.hbs

Set up the view skeleton for these two pages.
¯\\_(ツ)_/¯

Barebones magic link request / submit flow

---

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala
app/com/gu/identity/frontend/controllers/Application.scala
app/com/gu/identity/frontend/controllers/RepermissionController.scala
app/com/gu/identity/frontend/controllers/SigninAction.scala
app/com/gu/identity/frontend/controllers/SigninTokenController.scala
app/com/gu/identity/frontend/errors/HttpError.scala
app/com/gu/identity/frontend/models/text/ErrorPageText.scala
app/com/gu/identity/frontend/request/EmailSignInRequests.scala
app/com/gu/identity/frontend/services/IdentityService.scala
app/com/gu/identity/frontend/services/IdentityServiceRequestHandler.scala
app/com/gu/identity/service/client/ApiResponses.scala
app/com/gu/identity/service/client/IdentityClient.scala
app/com/gu/identity/service/client/request/RegisterApiRequest.scala
app/com/gu/identity/service/client/request/SendSiginInTokenEmailApiRequest.scala
app/com/gu/identity/service/client/request/SigninTokenRequest.scala
conf/messages.en
conf/routes

frontend endpoints for magic link signin

Magic link exchange

---

app/com/gu/identity/frontend/models/Text.scala
conf/messages.en
public/components/two-step-signin/two-step-signin-existing.hbs
public/components/two-step-signin/two-step-signin-guest.hbs
public/components/two-step-signin/two-step-signin-new.hbs

Adds social sign ins to all step footers. Now that everything's there I'll tidy up the design of all three flows on a subsequent PR.
In the meantime look at this magnificent monster of a page. This choose your own adventure book of a register flow:

Add social links to all steps of 2 step sign in

---

app/com/gu/identity/frontend/controllers/SigninAction.scala
app/com/gu/identity/frontend/models/text/SendSignInLinkSentText.scala
app/com/gu/identity/frontend/views/models/LayoutViewModel.scala
app/com/gu/identity/frontend/views/models/SendSignInLinkSentViewModel.scala
app/com/gu/identity/frontend/views/models/SendSignInLinkViewModel.scala
conf/messages.en
conf/routes
public/components/ajax-step-flow/_valid-routes.js
public/components/form/_form.css
public/send-sign-in-link-sent.hbs
public/send-sign-in-link.hbs

I believe once this is merged we can begin to use it live!
Should we be collecting any GA metrics? might be useful.

Add form for the MLST (magic link sender tool)

---

app/com/gu/identity/frontend/models/text/SendSignInLinkText.scala
app/com/gu/identity/frontend/views/models/SendSignInLinkViewModel.scala
conf/messages.en
public/components/_typography.css
public/components/form/_form.css
public/send-sign-in-link-sent.hbs
public/send-sign-in-link.hbs

- Update copy
- Use gu.com/swu as returnUrl

Update newsletters link send tool copy

---

app/com/gu/identity/frontend/controllers/SigninTokenController.scala
app/com/gu/identity/frontend/services/IdentityService.scala
build.sbt

- Exchange a resub-token for an RP cookie instead of a full cookie.

Resub emails now issue an RP cookie, bump library versions

---

conf/messages.en
public/_html.css

Lines up the copy with K's latest, removes a visible but unneeded focus ring over `main`

Minor Copy & UX improvements

---

public/_html.css
public/_layout.css
public/components/_typography.css
public/components/ajax-step-flow/_ajax-step-flow.css
public/components/ajax-step-flow/ajax-step-flow.js
public/components/sentry/sentry.js
public/components/two-step-signin/two-step-signin-existing.hbs
public/components/two-step-signin/two-step-signin-guest.hbs
public/components/two-step-signin/two-step-signin-new.hbs
public/components/two-step-signin/two-step-signin-start.hbs
public/send-resub-link.hbs

DIdn't get around to doing this until now! Now they will make sense for screen readers!

Fix labels for forms

---

app/com/gu/identity/frontend/controllers/Application.scala
app/com/gu/identity/frontend/controllers/SigninAction.scala
app/com/gu/identity/frontend/models/EmailProvider.scala
app/com/gu/identity/frontend/models/text/SendSignInLinkSentText.scala
app/com/gu/identity/frontend/views/ViewRenderer.scala
app/com/gu/identity/frontend/views/models/SendSignInLinkSentViewModel.scala
conf/messages.en
conf/routes
public/send-sign-in-link-sent.hbs

Add webmail links to resub-email/email-sent

---

app/com/gu/identity/frontend/analytics/client/MeasurementProtocolClient.scala
app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala
app/com/gu/identity/frontend/csrf/CSRFToken.scala
app/com/gu/identity/frontend/filters/Filters.scala
app/com/gu/identity/frontend/filters/HtmlCompressorFilter.scala
app/com/gu/identity/frontend/filters/LogRequestsFilter.scala
app/com/gu/identity/frontend/filters/StrictTransportSecurityHeaderFilter.scala
app/com/gu/identity/frontend/services/IdentityServiceRequestHandler.scala
app/com/gu/identity/frontend/utils/ErrorRecoveryActionBuilder.scala
build.sbt
project/plugins.sbt
test/com/gu/identity/frontend/authentication/UserAuthenticatedActionSpec.scala
test/com/gu/identity/frontend/controllers/ConsentControllerSpec.scala
test/com/gu/identity/frontend/controllers/RegisterActionSpec.scala
test/com/gu/identity/frontend/controllers/ResetPasswordActionSpec.scala
test/com/gu/identity/frontend/controllers/SignOutActionSpec.scala
test/com/gu/identity/frontend/controllers/SigninActionSpec.scala
test/com/gu/identity/frontend/controllers/ThirdPartyTsAndCsSpec.scala

Migrate form Play 2.4 to 2.5
https://www.playframework.com/documentation/2.6.x/Migration25

Migrate to play 2.5

---

conf/messages.en

Update wording (sign into) => (sign in to)

---

public/components/layout/_layout.css
public/css/_html.css

Squash some minor CSS issues from #412's code cleanup

fix css bugs

---

public/components/form/form-feedback-wrap.hbs
public/components/form/form-feedback-wrap.js

Fixes two minor layout bugs (misplaced errors & wrong CSS class names) I found while working on a bigger task

Improve 2 step sign in error reporting

---

public/change-email-page.hbs
public/components/form/_form-button.css

Email changed buttons were coloured purple instead of black

fix email change buttons

---

app/com/gu/identity/frontend/controllers/Application.scala
app/com/gu/identity/frontend/models/text/ReactIslandFallbackText.scala
app/com/gu/identity/frontend/views/ViewRenderer.scala
app/com/gu/identity/frontend/views/models/CollectConsentsViewModel.scala
conf/messages.en
conf/routes
public/collect-consents.hbs
public/components/layout/_layout.css
public/components/react-island/_react-island__fallback.css
public/components/react-island/_react-island__fallback.hbs
public/components/recurringContributions/_recurringContributions.css
public/components/smartlock-trigger/smartlock-trigger.js
public/main.css

Nothing to see here yet, this PR just puts the view controllers and such in place. 
This is a chunk of #428 that I've split up for cleanliness. I also threw in the handlebars parts of the islands and worked on those a bit more

Initial version of /collect-consents

---

public/components/sentry/sentry.js

Used the wrong name for releases

Sentry bugfixes

---

conf/routes
test/com/gu/identity/frontend/authentication/UserAuthenticatedActionSpec.scala

This is a bit of a hack with https://github.com/guardian/identity-platform/pull/259

Always 2step signin

---

app/com/gu/identity/frontend/controllers/ThirdPartyTsAndCs.scala
app/com/gu/identity/frontend/errors/AppException.scala
app/com/gu/identity/frontend/errors/ErrorID.scala
app/com/gu/identity/frontend/errors/GetUserAppException.scala
app/com/gu/identity/service/client/Errors.scala
conf/DEV.conf

- Frontend should redirect to reauthenticate if identity-api returns a 401
- Currently we just display a an error page.

Fix frontend dealing with 401

---

.browserslistrc
package-lock.json
package.json
postcss.config.js
public/js/get-url-errors.js

we had a bit of polyfill troubles. it's all good now.

Fix sign in on iOS8

---

public/components/form/_form-button.global.css
public/css/globals/_vars.css

Update the colour palette
