circle.yml
Use `sbt riffRaffUpload` to package and upload artifact to S3 for riffraff deployment.
=> Enable upload to riffraff on Circle CI

conf/routes, postcss.json, webpack.config.js
Renamed `/assets` route to `/static` to avoid potential collisions with old app.
=> Route assets on /static

app/com/gu/identity/frontend/views/ViewRenderer.scala, app/com/gu/identity/frontend/views/models/SignInViewModel.scala, public/signin-page.hbs
Fixes for:
- Forgot password link was in the wrong spot
- Register and Forgot password links were not resolving
Due to merge conflicts in #30
=> Fix broken links on sign-in form

app/com/gu/identity/service/client/ApiRequests.scala, test/com/gu/identity/service/client/AuthenticateCookiesRequestSpec.scala
Fixes issues with % signs in passwords.
=> Ensure body params are URL encoded

.prout.json
...so that it can hit the manifest endpoint https://profile-origin.code.dev-theguardian.com/management/manifest - and doesn't say that https://github.com/guardian/identity-frontend/pull/38 is overdue.
See also https://github.com/guardian/prout/pull/16
cc @mario-galic
=> Tell Prout to disable SSL verification for CODE

app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/controllers/SigninAction.scala, app/com/gu/identity/frontend/models/ReturnUrl.scala, app/com/gu/identity/frontend/views/ViewRenderer.scala, app/com/gu/identity/frontend/views/models/SignInViewModel.scala, test/com/gu/identity/frontend/models/ReturnUrl$Test.scala
This PR implements redirecting the user back to the Referer when the returnUrl is not set by query parameter.  This is the same behaviour that exists on the existing dotcom::identity solution.
=> Referer return url

app/com/gu/identity/frontend/views/models/SignInViewModel.scala, test/com/gu/identity/frontend/models/ReturnUrlSpec.scala, test/com/gu/identity/frontend/views/models/UrlBuilderSpec.scala
Ensures the Return URL and other parameters are encoded when appended to links in the views, such as the Social Sign in links.
=> Fix Return URL encoding for links

functional-tests/build.sbt, functional-tests/src/test/resources/application.conf, functional-tests/src/test/resources/logback.xml, functional-tests/src/test/scala/SigninSpec.scala, functional-tests/src/test/scala/pages/FacebookAuthDialog.scala, functional-tests/src/test/scala/pages/FacebookLogin.scala, functional-tests/src/test/scala/pages/Homepage.scala, functional-tests/src/test/scala/pages/Register.scala, functional-tests/src/test/scala/pages/RegisterConfirm.scala, functional-tests/src/test/scala/pages/Signin.scala, functional-tests/src/test/scala/util/Config.scala, functional-tests/src/test/scala/util/LoadablePage.scala, functional-tests/src/test/scala/util/user/EmailTestUser.scala, functional-tests/src/test/scala/util/user/FacebookTestUser.scala, functional-tests/src/test/scala/util/user/TestUser.scala
@jamespamplin @nlindblad 
[Example screencast](https://saucelabs.com/tests/33a8d46ffe0e4d059593017293d2706f)
Added 'Register with Facebook' test which uses [Facebook Test User API](https://developers.facebook.com/docs/apps/test-users) to generate Facebook users, as opposed to using a hard-coded user.
This test corresponds to the old [SN1 test](https://github.com/guardian/identity-functional-tests/blob/master/identity-tests/src/test/scala/com/gu/identity/integration/test/features/SocialNetworkTests.scala#L25)
=> Add Facebook registration test

functional-tests/src/test/scala/pages/FacebookAuthDialog.scala
@jamespamplin 
Facebook is randomising ID attribute of `'Edit the info you provide'`. Sometimes the ID is u_0_q, and other times u_0_s. Thus it needs to be located by inner text.
=> Locate by inner text due to FB randomization

functional-tests/src/test/resources/application.conf, functional-tests/src/test/scala/SigninSpec.scala, functional-tests/src/test/scala/pages/FacebookAuthDialog.scala, functional-tests/src/test/scala/pages/FacebookLogin.scala, functional-tests/src/test/scala/pages/GoogleAccounts.scala, functional-tests/src/test/scala/pages/Register.scala, functional-tests/src/test/scala/pages/RegisterConfirm.scala, functional-tests/src/test/scala/pages/Signin.scala, functional-tests/src/test/scala/util/Browser.scala, functional-tests/src/test/scala/util/Config.scala, functional-tests/src/test/scala/util/user/EmailTestUser.scala, functional-tests/src/test/scala/util/user/FacebookTestUser.scala, functional-tests/src/test/scala/util/user/GoogleTestUser.scala, functional-tests/src/test/scala/util/user/TestUser.scala
@jamespamplin 
[Example screencast](https://saucelabs.com/beta/tests/2e229beff72f4a26984967868ef3ca6b/commands)
Added test scenario:
`Existing users sign in with Google.`
Since Google does not provide a similar Test User API to [Facebook](https://developers.facebook.com/docs/graph-api/reference/v2.5/test-user) we are using a hardcoded Google user "Bob Test". Thus we can test just the sign in functionality, and not the full registration via Google.
The relevant lines of code are [SigninSpec.scala#192-211](https://github.com/guardian/identity-frontend/compare/fun-tests-google-signin?expand=1#diff-8fa20870fda6f35709c81a4110121941R192). The rest is some refactoring of utilities and factoring out [test fixtures](http://www.scalatest.org/user_guide/sharing_fixtures).
=> Add 'Existing users sign in with Google' test

public/_layout.css, public/components/footer/_footer.css, public/components/form-foundations/_form_foundations.css, public/components/oauth-cta/_oauth-cta.css, public/components/register-form/_register-form.hbs, public/components/signin/_signin.css, public/signin-page-b.hbs, public/signin-page.hbs
- Don't hide original checkboxes so that they are focusable
- Glow styles on fields when focused
- Form colours extracted to variables
- Improvements to keyboard nav
Fixes #55
=> Improve focus styles

app/com/gu/identity/frontend/views/models/LayoutViewModel.scala, app/com/gu/identity/frontend/views/models/PageResources.scala, conf/routes, frontend.sbt, project/plugins.sbt
Use [`sbt-digest`](https://github.com/sbt/sbt-digest) to create hashes of assets on package compilation, which Play can use at runtime to cache the asset for a looonnnggg time.
Note: only works when app is running in production mode.
=> Long life caching of Assets

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala, app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/controllers/RegisterAction.scala, app/com/gu/identity/frontend/controllers/SigninAction.scala, app/com/gu/identity/frontend/csrf/CSRFActions.scala, app/com/gu/identity/frontend/csrf/CSRFConfig.scala, app/com/gu/identity/frontend/csrf/CSRFToken.scala, app/com/gu/identity/frontend/csrf/package.scala, app/com/gu/identity/frontend/views/ViewRenderer.scala, app/com/gu/identity/frontend/views/models/ErrorViewModel.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, app/com/gu/identity/frontend/views/models/SignInViewModel.scala, conf/application.conf, project/plugins.sbt, public/components/register-form/_register-form.hbs, public/signin-page-b.hbs, public/signin-page.hbs, test/com/gu/identity/frontend/controllers/RegisterActionSpec.scala, test/com/gu/identity/frontend/controllers/SigninActionSpec.scala, test/com/gu/identity/frontend/csrf/CSRFActionsSpec.scala, test/com/gu/identity/frontend/test/SimpleAppPerSuite.scala, test/com/gu/identity/frontend/test/SimpleFakeApplication.scala
Uses adapters around play's CSRF filters / API to use request tokens to prevent CSRF attacks.
Added to both Sign in and Registration endpoints.
=> CSRF validation

app/com/gu/identity/frontend/controllers/RegisterAction.scala
Fixes an issue on PROD / CODE where the group code is on the redirect when an error occurs. This causes fastly to route to the old sign in form which doesn't show the error.
=> Fix issue where empty group code is in redirect URL on errors

package.json, public/components/browser/storage.js, public/components/lib/lodash.js, public/components/register-form/register-form.js, public/components/signin/signin.js, public/main.js, webpack.config.js
Remember form inputs on Register page using session storage in the browser as persistence.
- Uses classes to model the Register form, fields, and state
- Updated logic for sign in field persistence to match Register's
- Added lodash as a dependency, only using `mapValues` for now
- Changed webpack config to not mangle JS variables with Uglify, aids with debugging
=> Remember form inputs on Register page

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala, conf/routes
Moved Content Security Policy endpoint under /actions to avoid having to have another route whitelisted in the fastly routing config.
=> Move CSP report endpoint

functional-tests/src/test/scala/util/user/FacebookTestUser.scala
@jamespamplin 
Fixes the [following](http://build.capi.gutools.co.uk/viewLog.html?buildId=1053&tab=buildResultsDiv&buildTypeId=Identity_FunctionalTests_IdentityFrontend) error that sometimes occurs when hitting Facebook Graph API:
```
{"error":{"message":"An unknown error has occurred.","type":"OAuthException","code":1,"fbtrace_id":"ACcRWVUlPbe"}}
```
by retrying the call up to 5 times. 
Implemented using tail recursion.
=> Fix intermittent Facebook OAuthException

app/com/gu/identity/frontend/views/models/ContentSecurityPolicy.scala, app/com/gu/identity/frontend/views/models/LayoutViewModel.scala, app/com/gu/identity/frontend/views/models/PageResources.scala, public/components/analytics/mvt-model.js, public/components/analytics/mvt.js, public/components/analytics/omniture.js, public/components/browser/dom-element.js, public/components/configuration/configuration.js, public/layout.hbs
Found an issue related to CSP and Firefox version < 43, where only CSP 1.0 is properly supported. Hashes of inlined scripts are not supported in this browser resulting in client errors.
This PR changes the config from an inlined script to be statically injected into the response into a `<script type="application/json">` tag, then parsed via the Javascript when it initialises.
=> Better Content-Security-Policy 1.0 support

functional-tests/src/test/scala/util/user/FacebookTestUser.scala
@jamespamplin 
Solves [Future timeout](http://build.capi.gutools.co.uk/viewLog.html?buildId=1089&tab=buildResultsDiv&buildTypeId=Identity_FunctionalTests_IdentityFrontend) issue when calling Facebook API:
```
java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
```
=> Retry on synchronous call timeout

app/com/gu/identity/frontend/configuration/Configuration.scala, app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala, app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/controllers/RegisterAction.scala, app/com/gu/identity/frontend/controllers/SigninAction.scala, app/com/gu/identity/frontend/models/ReturnUrl.scala, app/com/gu/identity/frontend/models/UrlBuilder.scala, conf/CODE.conf, conf/DEV.conf, conf/PROD.conf, test/com/gu/identity/frontend/controllers/SigninActionSpec.scala, test/com/gu/identity/frontend/models/ReturnUrlSpec.scala
Addresses 3 tech debt issues with return url:
- If the return url is the default return url (i.e. http://www.theguardian.com) it is not included as a query param in the url to make the url cleaner
- Ignore return url and referrer header if they are the url for the sign in page, register page or register confirmation page.
- The default return url should be environment specific
=> Return url tech debt

app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/mvt/MultiVariantTestAction.scala, app/com/gu/identity/frontend/mvt/MultiVariantTestID.scala, app/com/gu/identity/frontend/mvt/MultiVariantTests.scala, app/com/gu/identity/frontend/mvt/TestResults.scala, app/com/gu/identity/frontend/mvt/package.scala, app/com/gu/identity/frontend/views/ViewRenderer.scala, app/com/gu/identity/frontend/views/models/LayoutViewModel.scala, app/com/gu/identity/frontend/views/models/RegisterConfirmationViewModel.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, app/com/gu/identity/frontend/views/models/SignInViewModel.scala, test/com/gu/identity/frontend/mvt/MultiVariantTestsSpec.scala
Fixes an issue on PROD where test results may be omitted when a `GU_mvt_id` cookie is not present by defining default variants on tests with 100% participation.
Also addresses some tech debt raised in #53:
- Moved all MVT stuff to `mvt` package
- Moved a lot of code out of `MultiVariantTests.scala` so that now it only contains Test definitions
- Created `ActiveMultiVariantTests` type definition for active test results instead of `Iterable[(MultiVariantTest, MultiVariantTestVariant)]` for better readability
=> Ensure test results recorded for 100% tests

frontend.sbt, project/FrontendBuildPlugin.scala
- Fixes issue where both build-css and build-js commands run whenever a
css file or a js file are modified. Caused by the CSS task incorrectly
including the built JS source map as its task output, causing its
incremental cache to invalidate.
- Also added debug logs for easier debugging of task outputs. Use `last`
in sbt to see debug logs.
=> Fix issue where asset build triggers twice

app/com/gu/identity/frontend/services/IdentityServiceRequestHandler.scala, app/com/gu/identity/service/client/ApiRequests.scala, test/com/gu/identity/frontend/services/IdentityServiceRequestHandlerSpec.scala
Fixes the following missing fields when registering new users:
- Surname should be `secondName` as required by the API
- `receiveGnmMarketing` should be in a `statusFields` object
- `receive3rdPartyMarketing` should be in a `statusFields` object
=> Fix missing fields when Registering

app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/views/ViewRenderer.scala, app/com/gu/identity/frontend/views/models/RegisterConfirmationViewModel.scala
From the PEN test report:
A URL variable passed between the client and server was subsequently used to create a hyperlink and embed it in the page: https://profile.theguardian.com/register/confirm?returnUrl=http%3A%2F%2Fwww.corsaire.com By sending crafted links to users of the system, it would be possible to include third party content in the context of the application, and engage in phishing attacks, for example.
=> Fix: P7282.F05 User-controlled client-side redirect

README.md, conf/DEV.conf
We've made it possible to grant other team accounts access to the S3 objects mentioned in the README.
This update provides more information about that.
=> Update README to reflect S3 policies

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala, app/com/gu/identity/frontend/filters/HtmlCompressorFilter.scala
By default, the Google HTML Compressor will remove http protocol from href and src attributes, this change takes the defaults and modifies it so that the http protocol is preserved in the response.
Fixes issue where a Return URL requiring http will incorrectly link to https on the register confirm page due to the compressor removing the protocol from the link, eg:
https://profile.code.dev-theguardian.com/register/confirm?returnUrl=http%3A%2F%2Fm.code.dev-theguardian.com
=> Fix removal of http protocol from links

app/com/gu/identity/frontend/models/Text.scala, app/com/gu/identity/frontend/models/text/FooterText.scala, app/com/gu/identity/frontend/views/models/LayoutViewModel.scala, conf/messages.en
Dynamically update the year in the footer copyright.
Note: requires that the apps are restarted / deployed when the year changes.
=> Live in the present

app/com/gu/identity/frontend/mvt/MultiVariantTests.scala
MVT Tests `IdentitySignInV2` and `IdentityRegisterV2` are no longer needed as we're at 100% on PROD now.
=> Removed finished MVT tests

frontend.sbt, project/FrontendBuildPlugin.scala
- Removes node_modules directory on `clean` task
- Logs to the user that the node_modules have been deleted, so the next
compile may be slow
- Log before node modules are installed for the first time, so the user
will know it will take some time
=> Remove node_modules on `sbt clean`

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala, app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/controllers/Redirects.scala, conf/routes
- New Redirects controller for all redirects
- Legacy routes log request uri and referrer, redirect with permanent
redirect code
Legacy routes for `/signin/` and `/register/` are being reported in the logs as 404. This should fix these.
=> Capture legacy routes and redirect

app/com/gu/identity/frontend/configuration/Configuration.scala, app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/controllers/RegisterAction.scala, app/com/gu/identity/frontend/controllers/SigninAction.scala, app/com/gu/identity/frontend/models/ReturnUrl.scala, app/com/gu/identity/frontend/views/models/LayoutViewModel.scala, app/com/gu/identity/frontend/views/models/RegisterConfirmationViewModel.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, app/com/gu/identity/frontend/views/models/ResetPasswordEmailSentViewModel.scala, app/com/gu/identity/frontend/views/models/ResetPasswordViewModel.scala, app/com/gu/identity/frontend/views/models/SignInViewModel.scala, conf/CODE.conf, conf/DEV.conf, conf/PROD.conf, conf/application.conf, public/components/footer/_footer.hbs, public/components/header/_header.hbs, test/com/gu/identity/frontend/models/ReturnUrlSpec.scala
- Back button uses `returnUrl` to determine its link
- Logo link will go to membership when `clientId=members`
- `returnUrl` will fallback to membership when `clientId=members`
- Use a model for the header and footer links of the layout
=> Make back button go back (and members logo link go to membership)

app/com/gu/identity/frontend/services/IdentityServiceRequestHandler.scala, app/com/gu/identity/service/client/IdentityClient.scala, app/com/gu/identity/service/client/request/SendResetPasswordEmailApiRequest.scala, test/com/gu/identity/frontend/services/IdentityServiceRequestHandlerSpec.scala
Replaces the call to the Identity API pwd-reset endpoint (POST instead of GET)
=> Replace send password email endpoint

app/com/gu/identity/frontend/models/text/OAuthText.scala, app/com/gu/identity/frontend/mvt/MultiVariantTests.scala, app/com/gu/identity/frontend/views/models/OAuthViewModel.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, app/com/gu/identity/frontend/views/models/SignInViewModel.scala, conf/messages.en, public/components/oauth-cta/_oauth-cta.css, public/components/oauth-cta/_oauth-cta.hbs
This PR tests additional copy around social sign-in to encourage the usage of these authentication methods.
See [Test Parameters](https://docs.google.com/document/d/1rNZWBpS7CMnO74uya9UX3l76vqRdydKOvhyZKY4qOMY/edit#heading=h.i2h2thoif3nr) for more detail.
=> Add a/b test for social permissions copy

public/components/form-foundations/_form_foundations.css
Fixes the following issue where the fieldset for the signin and reg forms has an unwanted collapsed margin in Safari.
=> Fix fieldset size in Safari

app/com/gu/identity/frontend/authentication/UserAuthenticatedAction.scala, app/com/gu/identity/frontend/controllers/RegisterAction.scala, app/com/gu/identity/frontend/controllers/ThirdPartyTsAndCs.scala, app/com/gu/identity/frontend/models/GroupCode.scala, app/com/gu/identity/frontend/models/UrlBuilder.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, app/com/gu/identity/frontend/views/models/SignInViewModel.scala, app/com/gu/identity/frontend/views/models/TermsViewModel.scala, app/com/gu/identity/frontend/views/models/TsAndCsViewModel.scala, public/components/register-form/_register-form.hbs, public/components/signin-form/_signin-form.hbs
This change fixes an issue with the group code not being rendered in the Handlebars templates.
`GroupCode` has been changed to follow the same pattern as for `ClientId`.
=> Fix handlebars for terms and conditions

app/com/gu/identity/frontend/configuration/Configuration.scala, app/com/gu/identity/frontend/views/models/ContentSecurityPolicy.scala, app/com/gu/identity/frontend/views/models/LayoutViewModel.scala, app/com/gu/identity/frontend/views/models/PageResources.scala, conf/application.conf, package.json, public/components/configuration/configuration.js, public/components/sentry/sentry.js, public/main.js
Initial Sentry integration in Javascript. Will log JS errors with Sentry, associating the Git hash as the Release Version for tracking errors between releases.
For example, this: [reported error](https://app.getsentry.com/the-guardian/identity-frontend-dev/issues/117568067/)
=> Sentry integration in JS

public/components/analytics/ophan.js, public/components/browser/storage.js, public/components/sentry/sentry.js
- Ignore all errors from Ophan (same as dotcom)
- Catch all sessionStorage errors and perform checks before using it
- Retry loading of Ophan script, in case of network error
=> Fixes for a few client-side errors reported in Sentry

app/com/gu/identity/frontend/errors/RegisterAppException.scala, app/com/gu/identity/frontend/models/TrackingData.scala, app/com/gu/identity/service/client/Errors.scala
Previously if the user entered an invalid email, the generic "one or more inputs
was not valid, please try again" message was displayed.
- Ensure that if the user enters an invalid email address, they are shown an error
saying ""Invalid email address; please try again."
=> #1202 Display specific error message on registration page for invalid email 

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala, app/com/gu/identity/frontend/logging/SuccessfulActionCloudwatchLogging.scala, cloudformation/identity-frontend.template
Sends a data point with a very small value to the CloudWatch Signin metric every 10 seconds. This makes sure the SigninInactivity alarm is never into an "INSUFFICIENT_DATA" state. Also updates the alarm to include the stage dimension
=> Cloudwatch small datapoints

app/com/gu/identity/frontend/models/text/TermsText.scala, app/com/gu/identity/frontend/views/models/TermsViewModel.scala, conf/messages.en
Oddly the vals in `TermsViewModel` did not propagate properly to HandleBars.
This makes them part of the case class, which ensures they get through correctly.
=> Fix broken Guardian T&C's links

cloudformation/identity-frontend.template
There is now a vulnerability scanner in the Identity account. This PR lets us add a Security Group to instances to allow vulnerability scans.
=> Add SG parameter for Vulnerability Scanning

public/components/register-form/_register-form.hbs
**Before**:
**After**:
It was already checking the format, but the native error message is not very helpful without a `title` attribute.
Based on http://www.html5rocks.com/en/tutorials/forms/constraintvalidation/
=> Add additional helper for Chrome native form hint

public/components/lib/phone-field.js, public/components/register-form/_register-form.hbs, public/components/register-form/register-form.js
When the form is persisted in local storage the country code gets lost for two reasons.
1. The fields are update after storing in local storage
2. The stored field is never used to change the initial country
This PR fixes both, when you register and validation brings you back to the form, the country flag should be the same as what you previously selected
@guardian/identity @NathanielBennett
=> Remember the country code on phone validation

app/com/gu/identity/frontend/mvt/MultiVariantTests.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, conf/messages.en
This PR adds a new standfirst for jobs.  (https://profile-origin.thegulocal.com/register?clientId=jobs).  It also removes the defunct membership standfirst test.
=> Add Jobs standfirst

deploy.json, project/plugins.sbt
- publicReadAcl
_[16:40:55] DEPRECATED: publicReadAcl should be specified for an autoscaling deploy. Not setting this means that it defaults to true which is insecure and probably not what you want. It is not a good idea for artifacts to be publically available on the internet - it is much better to ensure this is set to false and your instances download the artifact from S3 using IAM instance credentials. If you are CERTAIN that this iswhat you want you can also get rid of this message by explicitly setting publicReadAcl to true._
- Upgrade sbt-riffraff-artifact to latest version to ensure we are not reliant on legacy formats.
CODE build without warnings:
=> Fix Riff-Raff warnings

README.md
When setting up identity locally, trying to view the health check before installing the configuration file gives an error stating that you are missing `identity.api.key`.
Moved the instructions to view the health check after the section on installing the configuration file. Hopefully prevents devs who are setting up identity for the first time from hitting this error.
This is identical to #166, but made from a local branch, as test runner was failing with the forked branch.
=> Move Run Step After Configuration Install Step in Docs - Local Branch

cloudformation/identity-frontend.template
Trusted Advisor is reporting low CPU usage on these instances therefore reducing size to small.  This will reduce costs (slightly).
=> Use t2.small on PROD 

public/components/membership/_membership.css
Major update? Not really... tweaked the membership-specific signup/signin buttons from purple to the standard Guardian blue.
**Old:**
**New:**
=> Membership Signup/Signin Buttons - Reverted to Guardian Blue

.prout.json, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, public/register-page.hbs
Previously the manifest at https://profile-origin.theguardian.com/management/manifest
was the only way to get the Git commit id out of the profile site, unfortunately the certificate on that endpoint is only valid for `profile-beta.theguardian.com`, so Prout wouldn't read it, and declared all PRs overdue-on-PROD.
This fix is an alternative to https://github.com/guardian/identity-frontend/pull/173 ("Tell Prout not to worry about the cert on profile-origin.theguardian.com")
cc @markjamesbutler
=> Put the build commit id into the registration page so Prout can read it

app/com/gu/identity/frontend/configuration/Configuration.scala, app/com/gu/identity/frontend/models/ReturnUrl.scala, app/com/gu/identity/frontend/views/models/LayoutViewModel.scala, conf/application.conf, test/com/gu/identity/frontend/models/ReturnUrlSpec.scala
Michael Campbell (Digital Marketing Manager) pointed out that https://profile.theguardian.com/register?returnUrl=https://membership.theguardian.com/join/supporter/enter-details?countryGroup%3Duk%26INTCMP%3DMEM_HOME_SUP&skipConfirmation=true&clientId=members
had a Guardian Members logo that linked to https://membership.theguardian.com, a page that currently doesn't perform conversion as well as well as the supporter landing page.
So switching to link the 'Guardian Members' logo to the Supporter landing page instead!
@Ap0c
=> Use the Supporter landing page as the preferred Membership url

app/com/gu/identity/frontend/models/Text.scala, app/com/gu/identity/frontend/models/text/RegisterText.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, app/com/gu/identity/frontend/views/models/SignInViewModel.scala, conf/messages.en
Change title on the sign in and registration pages for people coming from the membership flow
'Create your Guardian account' becomes 'Create your Guardian account to become a member'
and  
'Sign in to the Guardian' becomes 'Sign in to the Guardian to become a member'.
More details:
https://trello.com/c/DdaKM6f6/84-update-text-on-create-account-sign-in-pages-to-allude-to-membership
=> Membership text changes

app/com/gu/identity/frontend/controllers/SignoutAction.scala, test/com/gu/identity/frontend/controllers/SignOutActionSpec.scala
This PR adds functionality to return the user to the page they were viewing before signing out when a return url is not provided on the signout request.  
It fixes this bug:
User navigates to: (https://www.theguardian.com/uk/business) and clicks Sign Out.  User is returned to: (https://www.theguardian.com/uk)  
Once this PR is deployed the user will be returned to: (https://www.theguardian.com/uk/business)
=> Use referrer if signout returnUrl isn't provided.

app/com/gu/identity/frontend/models/ReturnUrl.scala, test/com/gu/identity/frontend/models/ReturnUrlSpec.scala
The Jobs iOS app listens for the URL:
sso.com.theguardian.jobs://ssologoutsuccess
This PR whitelists this ReturnURL allowing Identity-Frontend to redirect to this valid URL.  I've including the entire URL narrow-down attack vectors.
=> Whitelist Jobs App URL

app/com/gu/identity/frontend/models/text/RegisterText.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, conf/messages.en
Currently, when a user wants to create a _Patron_ or a _Partner_ account and he or she is in the Flow B (`clientId=membersB`), the following identity screen is shown:
This lead to confusion of the user because "Supporter" is the name of one of the tiers.
When the user clicks on "Become a Patron" or "Become a Partner", we show **Become a Member** in the title.
=> Bug fix for the title of the sign up form in the Flow B of membership.

README.md
The certs expired already on 10th Nov. Updating the instructions to explain how to generate your own cert.
@guardian/identity
=> use openssl to generate a local cert

app/com/gu/identity/frontend/controllers/SignoutAction.scala, app/com/gu/identity/frontend/models/ReturnUrl.scala, test/com/gu/identity/frontend/controllers/ThirdPartyTsAndCsSpec.scala, test/com/gu/identity/frontend/models/ReturnUrlSpec.scala, test/com/gu/identity/frontend/models/UrlBuilderSpec.scala
Use case:
User is signed-in under the another account (shared device).  Allow sign-out and redirect to registration page.
N.B. Initially I attempted to use default parameters to archive this but scalac doesn't like this due to
`multiple overloaded alternatives of method apply define
default arguments.`
See [Why does the Scala compiler disallow overloaded methods with default arguments?](http://stackoverflow.com/questions/4652095/why-does-the-scala-compiler-disallow-overloaded-methods-with-default-arguments)
Therefore I added additional constructors to work around this.
=> Allow Sign Out to redirect to register page

public/components/membership/_membership.css, public/register-page-membership.hbs, public/signin-page-membership.hbs
The designer requested minor changes to the current implementation of the Sign up and Sign in form of membership. These forms are only applicable in the **flow B** of Sign in and Sign Up.
* `_membership.css`: Modified the `padding-left` property of the social buttons and the `font-size` of text fields. Finally, added `margin-bottom` for the bottom progess bar. The `font-weight` property of the button was already `normal`.
* `register-page-membership.hbs`: Changed the structure of the HTML. Moved the bottom progress bar inside the form, so we can use the [`flex-grow`](https://css-tricks.com/almanac/properties/f/flex-grow/) property.
* `signin-page-membership.hbs`: Same changes than above.
=> CSS changes to the Sign Up form for Flow B in members

app/com/gu/identity/frontend/request/RegisterActionRequestBody.scala, app/com/gu/identity/frontend/views/models/ErrorViewModel.scala, public/components/register-form-mem/_register-form-mem.hbs, public/components/register-form/_register-form.hbs, test/com/gu/identity/frontend/controllers/RegisterActionSpec.scala
I'm worried that the alphanumeric constraints on firstname, lastname and displayname in the register form are too strict and will prevent people with names such as O'hare or Rees-Mogg from registering.
As there doesn't seem to be a reason why these are here now that we are using displayname rather than username (which did require non-alphanumeric values) I think we should remove the constraints.
=> Loosen constraints on firstname, lastname and displayname

public/components/analytics/ga.js, public/components/signin-form/signin-form.js
This PR fires a GA custom metric when a user successfully authenticates using Smart Lock.  Additional PR's will be raised with more meta-data (ophanId etc) and log other events (regular sign-in etc) in the near future
=> GA Smart Lock Sign-in

app/com/gu/identity/frontend/views/models/RegisterViewModel.scala
@mario-galic is updating discussion to collect username on first comment.  Once this change has been merged we can remove display name entirely.  As displayname will be removed entirely once @mario-galic's change has been merged, I am simply hiding it for all clients.
=> Hide display name for all clients

app/com/gu/identity/frontend/authentication/AuthenticationService.scala, app/com/gu/identity/frontend/authentication/CookieName.scala, app/com/gu/identity/frontend/authentication/CookieService.scala, test/com/gu/identity/frontend/authentication/CookieServiceSpec.scala, test/com/gu/identity/frontend/controllers/SignOutActionSpec.scala
Now the site is fully [HTTPS](https://www.theguardian.com/info/developer-blog/2016/nov/29/the-guardian-has-moved-to-https) we can use a secure GU_U cookie to ensure data is sent of TLS.  
@adamnfish 
After registering locally:
=> Set GU_U secure flag to true

app/com/gu/identity/frontend/models/ClientID.scala, app/com/gu/identity/frontend/models/ReturnUrl.scala, app/com/gu/identity/frontend/models/text/RegisterText.scala, app/com/gu/identity/frontend/views/ViewRenderer.scala, app/com/gu/identity/frontend/views/models/LayoutViewModel.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, app/com/gu/identity/frontend/views/models/SignInViewModel.scala, conf/messages.en, public/components/membership/_membership.css, public/components/register-form-mem/_register-form-mem.hbs, public/components/register-form/_form-fields.hbs, public/components/register-form/_register-form.hbs, test/com/gu/identity/frontend/models/ReturnUrlSpec.scala
The checkout A/B test has finished. Flow B won the test. Therefore, we need to remove **membersB** from identity and the changes that were under membersB identifier, now will be under members.
**Old identity flow for Membership**
**New identity flow for Membership**
https://github.com/guardian/membership-frontend/pull/1416
=> Removed the second flow of membership

conf/CODE.conf, conf/DEV.conf, conf/PROD.conf
Updated the domain to meet [rfc2109](https://www.ietf.org/rfc/rfc2109.txt):
This is to prevent inconsistent behaviour across different browsers.
`Domain=domain
Optional.  The Domain attribute specifies the domain for which the
cookie is valid.  An explicitly specified domain must always start
with a dot.`
After:
=> Add . to cookie domain to meet rfc2109

conf/application.conf
=> Updated base url to https version to prevent (internal) redirect

app/com/gu/identity/frontend/views/models/ErrorViewModel.scala
We want to communicate the "already registered email" error better to users. 
* Change copy in Error messages.
=> Better copy for already registered email error.

public/components/signin-form-mem/_signin-form-mem.hbs
This template was missed when I originally added the custom GA metrics for sign-in and registration.  The same javascript/controller are used so it's just a case of adding the hidden field which will contain the GA client ID.
=> Add missing hidden GA field to members signin form

conf/DEV.conf
This reverts a change made in #210 to the DEV config. It changes the idapi and dotcom endpoints back to CODE, rather than `thegulocal`, so that we don't have to run these projects locally in order to use identity. This makes development on membership/support simpler.
=> Revert idapi And dotcom Endpoints Back To CODE

public/components/analytics/ga.js, public/components/oauth-cta/_oauth-cta.hbs, public/components/oauth-cta/_oauth-cta.js, public/components/register-form-mem/_register-form-mem.hbs, public/components/register-form/_register-form.hbs, public/components/register-form/register-form.js, public/components/signin-form-mem/_signin-form-mem.hbs, public/components/signin-form/_signin-form.hbs, public/components/signin-form/signin-form.js
This PR adds a `gaClientId` querystring parameter to the oauth links for signin and registration.  This client ID will be added to the state parameter sent to social providers in the federation API so that it can be used after successful sign in to send an event to GA.
I've also refactored how the client ID is added to the hidden field that is submitted with regular sign in.  This never belonged in the generic `ga.js` and now resides in `signin-form.js` and `register-form.js`.  It's not as DRY, but then neither are the components.  Wherever possible I have stayed consistent with the existing patterns (unlike before).
=> Send GA client ID to federation API

public/components/oauth-cta/_oauth-cta.js
Was checking the wrong URI for a the query string length.  This works most of the time because the oauth and profile URIs happen to share similar query strings - but there are edge cases where this breaks e.g. signing in with a deleted account.
=> Check the correct URI for adding GA client ID

app/com/gu/identity/frontend/configuration/Configuration.scala, app/com/gu/identity/frontend/views/models/RegisterConfirmationViewModel.scala, conf/messages.en, public/signin-page-membership.hbs, public/signin-page.hbs, test/com/gu/identity/frontend/controllers/RegisterActionSpec.scala, test/com/gu/identity/frontend/controllers/SignOutActionSpec.scala, test/com/gu/identity/frontend/controllers/SigninActionSpec.scala, test/com/gu/identity/frontend/controllers/ThirdPartyTsAndCsSpec.scala, test/com/gu/identity/frontend/models/ReturnUrlSpec.scala, test/com/gu/identity/frontend/models/UrlBuilderSpec.scala, test/com/gu/identity/frontend/utils/UrlDecoderSpec.scala, test/com/gu/identity/service/client/request/AuthenticateCookiesApiRequestSpec.scala, test/com/gu/identity/service/client/request/DeauthenticateApiRequestSpec.scala
These pages are now served directly on https so we can link to the https site directly.
=> Use HTTPS links to theguardian.com

.stylelintrc, public/components/_breakpoints.css, public/components/membership/_membership.css
New design for the membership skin. We get rid of the Guardian Members logo.
| Mobile | Mobile Landscape | Phablet | Tablet | Desktop | Wide |
|--------|------------------|---------|--------|---------|------|
|  ![identity-mobile](https://user-images.githubusercontent.com/825398/28276543-29eb574e-6b0f-11e7-9e1f-ccacff514b49.png)    | ![identity-mobile-landscape](https://user-images.githubusercontent.com/825398/28276401-b86187ba-6b0e-11e7-909c-a808824fdd8a.png)  |![identity-phablet](https://user-images.githubusercontent.com/825398/28276418-c97ed78c-6b0e-11e7-9e1c-8bfa0080d7c5.png) | ![identity-tablet](https://user-images.githubusercontent.com/825398/28276448-df9d78c0-6b0e-11e7-8f34-02eab05fc35a.png) | ![identity-desktop](https://user-images.githubusercontent.com/825398/28276391-b3005e54-6b0 …
=> New style for the membership/support header.

README.md, conf/DEV.conf
It seems we cannot use tilde ~ or environmental variables in `include file(...)`. Please see:
https://github.com/typesafehub/config/issues/122
To enable local config overrides relative to developer home directory we would need to implement this [in code](https://stackoverflow.com/questions/31570749/typesafe-config-file-in-home-directory) or use [guardian-configuration](https://github.com/guardian/guardian-configuration) library.
=> Config does not support tilde ~ in includes

app/com/gu/identity/frontend/request/RegisterActionRequestBody.scala, app/com/gu/identity/frontend/views/models/ErrorViewModel.scala, public/components/register-form/_form-fields.hbs
This removes the ability to create an account with the `:` or `/` characters in the first name or last name field.  We have seen an influx of accounts created like this.  Hopefully this change should mitigate that - although the ultimate goal would be to stop automated methods of creating accounts.
=> Disallow links in names

app/com/gu/identity/frontend/authentication/AuthenticationService.scala, app/com/gu/identity/frontend/authentication/CookieName.scala, test/com/gu/identity/frontend/authentication/AuthenticationServiceSpec.scala, test/com/gu/identity/frontend/controllers/SignOutActionSpec.scala
To include support for a new cookie being introduced on dotcom: `gu_recurring_contributor`. This is being used to mark someone as a recurring contributor, and to therefore hide supporter messaging for them. This cookie needs to be deleted on sign-out along with the other user cookies.
The corresponding branch (soon to become a PR in frontend) is [here](https://github.com/guardian/frontend/compare/stop-showing-messaging-for-recurring-contributors). Another corresponding PR in the members-data-api was merged today, and is [here](https://github.com/guardian/members-data-api/pull/230).
cc: @JustinPinner
- Added `gu_recurring_contributor` to the list of known cookies.
- Updated tests to include this new cookie.
=> Add Recurring Contributor Cookie

app/com/gu/identity/frontend/models/text/ThirdPartyTsAndCsText.scala, app/com/gu/identity/frontend/views/models/TermsViewModel.scala, conf/messages.en
The teacher's network has been updated and will now be using the 'use my existing account' page at `/agree/GTNF` for users who have an account but have not yet agreed to the additional teacher's network Ts&Cs.  This updates the wording on that page, and also the Ts&Cs/privacy links there and on the sign in page.
=> Update teachers Ts&Cs

cloudformation/identity-frontend.yaml
- Logging into Kibana was not working as there was no logstash.config file at /etc/logstash.config.
- An oversight from https://github.com/guardian/identity-frontend/pull/227 
- Tested on CODE.
=> Fix logstash config file

app/com/gu/identity/frontend/request/RegisterActionRequestBody.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, public/components/register-form/_form-fields.hbs, public/components/register-form/register-form.js, test/com/gu/identity/frontend/models/EmailValidationSpec.scala
Our email validation currently uses the standard Html 5 input validation and the Play email constraint. However both of these allow dotless domains on email addresses eg. test@gmail
These are now [prohibited by ICANN](https://www.icann.org/news/announcement-2013-08-30-en) and the likelihood is that anyone registering with one has actually just made a mistake. Dotless domains also cause problems when we try to use them to create user accounts in Salesforce.
A bit of research by @jfsoul reveals that we have 1,984 accounts with dotless domains of which none are actually valid.
This PR makes out email validation stricter to disallow dotless domains (see [EmailValidationSpec](https://github.com/guardian/identity-frontend/pull/231/files#diff-ffc2d94f9a4c37dd928a56af5bf4aab0) for a more in depth …
=> Email validation

cloudformation/identity-frontend.yaml
The fetching of SSH keys was not working after AMI creation due to this missing s3 permission.
=> Add permissions to fix SSH key fetching

build.sbt
[Sentry issue](https://sentry.io/the-guardian/identity-frontend-prod/issues/400660348/)
identity-cookie was compiled against older version of identity-model 3.51, so it could not pick up the new signature from identity-model 3.83.
```
NoSuchMethodError
com.gu.identity.model.User.<init>(Ljava/lang/String;Ljava/lang/String;Lcom/gu/identity/model/PublicFields;Lcom/gu/identity/model/PrivateFields;Lcom/gu/identity/model/StatusFields;Lcom/gu/identity/model/UserDates;Lscala/Option;Lscala/collection/mutable/Set;Lscala/collection/mutable/Set;Lscala/collection/mutable/Map;)V
com.gu.identity.cookie.GuUDecoder in cookieData2User at line 84
com.gu.identity.cookie.GuUDecoder$$anonfun$getUserDataForScGuU$1 in apply at line 881
com.gu.identity.cookie.GuUDecoder$$anonfun$getDataForScGuU$1 in apply at line …
```
=> Fix exception on agree journey

app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/views/ViewRenderer.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, app/com/gu/identity/frontend/views/models/SignInViewModel.scala, build.sbt, public/components/register-form/_form-fields.hbs, public/components/register-form/register-form.js, public/components/signin-form/_signin-form.hbs, public/components/signin-form/signin-form.js
We want to populate email address input boxes when users land /signin or /register pages with certain query params. 
- Parse the email from the url in the Applications.scala
- Pass the email from the backend to the handlebars template model and use this to prepopulate the email inputs.
-  Stop the javascript getting the email value from local storage if one has been passed in the model.
- Landing directly: `https://profile.theguardian.com/register?email=foo@bar.com`
- When redirected from another identity page e.g `https://profile.theguardian.com/public/edit?email=foo@bar.com` : `https://profile.thegulocal.com/signin?returnUrl=https%3A%2F%2Fprofile.thegulocal.com%2Fpublic%2Fedit%3Femailasd%3Dfoo%40bar.com` 
Relies on https://github.com/guardian/frontend/pull/18247
=> Parse email from url and use in frontend to pre-populate inputs

app/com/gu/identity/frontend/controllers/SigninAction.scala, conf/routes
- Pass a "journey" parameter in the token login endpoint.
- This will be passed to the successful redirect to as profile.theguardian/consent?journey=[repermission, signin,...]
- link will look something like _https://profile.thegulocal.com/actions/signin/consents/25FlkCgqELR8jObFLWepB3CyMZvTbs%2Fgqk7a3cqgCPJZhjlE60z2go%%3D%3D.z15GIEVc1x6HTxqA?journey=signup_
- This determines the consent mentioned in this pr : https://github.com/guardian/frontend/pull/18407
=> Pass journey parameter in token url

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala, app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/controllers/OptInController.scala, app/com/gu/identity/frontend/experiments/Experiment.scala, app/com/gu/identity/frontend/experiments/Experiments.scala, app/com/gu/identity/frontend/views/ViewRenderer.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, conf/routes, public/components/register-form/_form-fields.hbs
Copies over a slim version of `frontend`'s experiment tooling and adds a flag to hide the V1 consent checkboxes that can be set as true for the gdpr launch
https://profile.thegulocal.com/opt/in/stop-consent-collection
This merely sets a cookie (`x-gu-identity-$(consentName}`) which you can also set manually
=> [under flag] hide V1 consent checkboxes

build.sbt
Updates the version of `identity-library` to the one with final-ish V2 consent names that can be collected
=> Bump id-library version

app/com/gu/identity/frontend/configuration/Configuration.scala, app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/experiments/Experiments.scala
Changes the "show consent checkboxes on signup" switch to a config parameter so it's easier to flip it on launch day
=> Move consent collection to prefs

public/components/register-form/register-form.js, public/components/signin-form/signin-form.js
Some features of the credential management API (available in Chrome for smartlock) have being deprecated and we must migrate before Jan 23rd.
Notably I have decided to only support Chrome 60+. Users of older Chrome and other browsers will just not be able to use smartlock, normal sign in should work as usual though.  Will test this on CODE briefly and check in browser stack with older browsers.
Migration guide is here for reference: https://docs.google.com/document/d/154cO-0d5paDFfhN79GNdet1VeMUmELKhNv3YHvVSOh8/edit#heading=h.p0s1hn49u2f%E2%80%9D%20with%20%E2%80%9Chttps://docs.google.com/document/d/154cO-0d5paDFfhN79GNdet1VeMUmELKhNv3YHvVSOh8/edit%23
=> Update smart lock to avoid using deprecated features

conf/routes, public/invalid-consent-token-page.hbs
- Make the resend consentToken endpoint consistent with reset password by making it a GET endpoint.
- Consistent with endpoints setup in Fastly
=> Make resend consent token a get endpoint

conf/messages.en, public/_colors.css, public/_layout.css, public/components/footer/_footer.css, public/components/form-foundations/_form_foundations.css, public/components/form-foundations/arrow-right.svg, public/components/form-foundations/arrow-white-right.svg, public/components/header/_header.css, public/components/oauth-cta/_oauth-cta.css, public/components/register-form/_register-form.css, public/components/register-form/_register-form.hbs, public/components/reset-password/_reset-password.css, public/components/signin-form/_signin-form.css, public/components/signin-form/_signin-form.hbs, public/components/third-party-ts-and-cs/_third-party-ts-and-cs.css, public/register-confirmation-page.hbs, public/register-page.hbs, public/third-party-ts-and-cs-page.hbs
Implement a couple of visual changes to clean up the CSS + align with [Zef's mockup](https://www.figma.com/file/LkeSGB4PTbyNe6PSNCFnP7yM/Sign-in-page)
- Same height for inputs, & CTA's
- Footer now has capitalised authoritative looking links
- Fonts are less over the place in terms of sizing & classnames
- The max width is now a tad tinier so the logo doesn't go floating over the page on large screens
- The -or- thingy now has a divider running through it
- The background is grey, the cta's are yellow
=> Garnett touches

app/com/gu/identity/frontend/request/RegisterActionRequestBody.scala, test/com/gu/identity/frontend/models/EmailValidationSpec.scala
Userhelp received an email from a user who couldn't sign up because his email address has a single  letter for the name portion and our validation was failing this even though it is valid.
I've fixed the regex and added a new test case.
=> Add a new valid email case to the validation regex & test

app/com/gu/identity/frontend/request/RegisterActionRequestBody.scala, test/com/gu/identity/frontend/models/EmailValidationSpec.scala
'Smart quotes' are invalid within an email address name portion
=> Remove smart quote from list of valid characters

public/components/form-foundations/_form_foundations.css
Removes this pesky double checkbox out of sight, and out of mind
=> Fix checkboxes on Firefox

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala, app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/controllers/RepermissionController.scala, app/com/gu/identity/frontend/errors/DeauthenticateAppException.scala, app/com/gu/identity/frontend/errors/ErrorID.scala, app/com/gu/identity/frontend/services/IdentityService.scala, app/com/gu/identity/frontend/services/IdentityServiceRequestHandler.scala, app/com/gu/identity/service/client/IdentityClient.scala, app/com/gu/identity/service/client/request/UserRepermissionTokenRequest.scala, conf/routes
- Add endpoint /repermission-token/:token/accept 
- This will make a request to Identity api /repermission with a parameter of scopeToken=[token]
- If successful Identity will return a RP cookie
- If an RP cookie is received we will redirect the user to /consents (this may change if we get a specific repermisioning end point)
Currently using error page for invalid token until we make a dedicated expired token page.
Related ID PR = https://github.com/guardian/identity/pull/836
=> Endpoint to deal with repermission tokens

app/com/gu/identity/frontend/controllers/RepermissionController.scala
- Pick out the query string from the accept repermission token endpoint and pass it to the /consent redirect.
=> Process query string and pass to redirect on Repermission endpoint

app/com/gu/identity/frontend/controllers/RegisterAction.scala, functional-tests/src/test/scala/pages/RegisterConfirm.scala, test/com/gu/identity/frontend/controllers/RegisterActionSpec.scala
Link to `/complete-registration `, A more specifically-worded endpoint that replaces `/verify-email?isSignupFlow=true`. [See #frontend/19218](https://github.com/guardian/frontend/pull/19218)
=> link to /complete-registration

app/com/gu/identity/frontend/controllers/Application.scala
Reverts guardian/identity-frontend#302
This redirect is now implemented in identity-federation-api: https://github.com/guardian/identity-federation-api/pull/240
=> Revert "Add /email-prefs as registration return url"

app/com/gu/identity/frontend/models/Text.scala, app/com/gu/identity/frontend/views/models/TwoStepSignInViewModel.scala, conf/messages.en, public/_form.css, public/_html.css, public/_layout.css, public/components/terms/_terms-inline.hbs, public/components/terms/_terms.hbs, public/components/two-step-signin/_two-step-signin.css, public/components/two-step-signin/two-step-signin-email.hbs, public/components/two-step-signin/two-step-signin-existing.hbs, public/main.css, public/two-step-signin-choices-page.hbs, public/two-step-signin-start-page.hbs
While we are here I'm taking this opportunity to clean up the css and normalize it a bit, having global classes we can work with without needing extra boilerplate, so stuff like `.signin-page-remember-me__checkbox` becomes `.form-checkbox` and so on (example. not an actual change).
The new format also better acknowledges the reality of this design. The previous one had a quite complex wrapper structure since it had side borders and coloured sections while this one is rather plain.
This only applies to the css on the new two step signin but the eventual goal is to move all css (meaning the signup page if there's still a signup page; and third party terms) to this format after we assess what the rest of pages are and how they fit in this new flow.
=> Cleaner CSS for two step signin

app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/models/Text.scala, app/com/gu/identity/frontend/views/ViewRenderer.scala, app/com/gu/identity/frontend/views/models/ResetPasswordViewModel.scala, conf/messages.en, public/_form.css, public/components/two-step-signin/scriptFile.scala, public/components/two-step-signin/two-step-signin-guest.hbs, public/components/two-step-signin/two-step-signin-new.hbs, public/reset-password-page.hbs, public/two-step-signin-choices-page.hbs
Makes all three two step sign in pages actually work. The flows and messaging are still somewhat clunky for this PR but this brings it closer to a working prototype.
=> Add templates for all 3 signin types

README.md, package-lock.json, package.json, scripts/banner.js, watch-frontend.sh
Updates `npm run watch` to run sbt too. For doing only the assets it's `npm run watch-assets`.
i also put in this badass kitty on first loads, to cheer everybody's day
=> Make npm optionally run sbt too

public/_layout.css, public/components/register-form/register-form.js, public/components/two-step-signin/_two-step-signin.css, public/components/two-step-signin/two-step-signin-email.hbs, public/components/two-step-signin/two-step-signin-existing.hbs
- Makes email titles jump to 2 lines if an email won't fit. This doesn't look good, not gonna lie, but is better than trimming them for now.
- Fixes the slide animation flashing its opacity from 50% (loading) to 100% (animation) then 0% (animation end)
- Fixes `/signin/current` not submitting when a hidden field was using an invalid email
- Makes the smartlock code from register only pop in `/register` instead of all over the place. `/signin` (the old one) already has a handler and it was firing twice.
=> Minor css & js bugfixes

build.sbt
https://www.playframework.com/documentation/2.6.x/AssetsOverview#Reverse-routing-and-fingerprinting-for-public-assets
=> Enable asset fingerprinting

app/com/gu/identity/frontend/models/ReturnUrl.scala, test/com/gu/identity/frontend/models/ReturnUrlSpec.scala
Change the returnUrl parser so all urls whose path begins with `/signin` or `/register` count as invalid now, instead of only exact matches
=> prevent returnUrl from being /signin/{anything}

app/com/gu/identity/frontend/views/models/LayoutViewModel.scala, public/js/config.js, public/js/get-url-errors.js
This PR sends over to the client the error messages for all possible errors, this will let the 2 step sign in javascript flow pick them up and display them without an extra pageload
There's also a helper method that takes a url as a string and returns an array of errors found within it. This is all prep for the 2 step signin js code.
=> Send error code -> error text mapping to javascript

app/com/gu/identity/frontend/analytics/AnalyticsEventActor.scala, app/com/gu/identity/frontend/analytics/client/MeasurementProtocolClient.scala, app/com/gu/identity/frontend/analytics/client/MeasurementProtocolRequest.scala, app/com/gu/identity/frontend/controllers/SigninAction.scala, app/com/gu/identity/frontend/logging/MetricsActor.scala, app/com/gu/identity/frontend/logging/SuccessfulActionCloudwatchLogging.scala
Send a `SigninFirstStepSuccessful` to GA when an email is entered in the first field of two step signup. we can use this to track funnels and see how many people drop out after that
=> Track email inputs in GA

app/com/gu/identity/frontend/views/models/TwoStepSignInViewModel.scala, public/components/two-step-signin/two-step-signin-guest.hbs
Clicking the set password button will automatically send the email and drive the user to the confirmation page
=> Remove reset password page from /signin/guest flow

public/_html.css
Prevent the button from jumping to two lines (ugly!) until the viewport reaches phone sizes. Requested by @katyabeer
=> Tighter breakpoint for the [sign up] link

app/com/gu/identity/frontend/controllers/SigninAction.scala, app/com/gu/identity/frontend/views/models/TwoStepSignInViewModel.scala, conf/routes, public/components/two-step-signin/two-step-signin-existing.hbs
- When an existing user gets to the second step in the two step sign in , this posts to an endpoint that will redirect back to the second step (/signin/current) if the password is wrong or there is an error. Previously this would result in a redirect to /signin.
=> New endpoint and redirect for existing users to post password to

app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala, app/com/gu/identity/frontend/controllers/RegisterAction.scala, app/com/gu/identity/frontend/controllers/ResendConsentTokenAction.scala, app/com/gu/identity/frontend/controllers/ResendRepermissionTokenAction.scala, app/com/gu/identity/frontend/controllers/ResetPasswordAction.scala, app/com/gu/identity/frontend/controllers/SigninAction.scala, app/com/gu/identity/frontend/request/EmailResubRequests.scala, app/com/gu/identity/frontend/request/FormRequestBodyParser.scala, app/com/gu/identity/frontend/request/RegisterActionRequestBody.scala, app/com/gu/identity/frontend/request/ResendTokenActionRequestBody.scala, app/com/gu/identity/frontend/request/ResetPasswordActionRequestBody.scala, app/com/gu/identity/frontend/request/SignInActionRequestBody.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, test/com/gu/identity/frontend/controllers/RegisterActionSpec.scala, test/com/gu/identity/frontend/controllers/ResetPasswordActionSpec.scala, test/com/gu/identity/frontend/controllers/SigninActionSpec.scala, test/com/gu/identity/frontend/models/EmailValidationSpec.scala
Addresses `BodyParsers.parse` deprecation warning:
```
@deprecated("Inject PlayBodyParsers or use AbstractController instead", "2.6.0")
```
=> Remove custom parser hardwiring

app/com/gu/identity/frontend/configuration/Configuration.scala
This was accidentally removed in https://github.com/guardian/identity-frontend/pull/401/files
=> Revert removing the credentials

public/components/form/_form.css, public/components/layout/_layout.css, public/css/_html.css, public/css/_vars.css
Remove `--color-text-light ` and make all text `#121212` instead. The visual changes are barely noticeable but this one passes WAI AAA contrast standards
=> Fix text contrast

public/components/analytics/ga.js, public/components/signin-form/_signin-form.hbs, public/components/signin-form/signin-form.js, public/components/smartlock-trigger/smartlock-trigger.js
The smartlocksignin event is being sent twice to GA at the moment. This removes the client side sending
=> Remove dupe smartLockSignIn metric

app/com/gu/identity/frontend/analytics/client/MeasurementProtocolRequest.scala, app/com/gu/identity/frontend/configuration/FrontendApplicationLoader.scala, app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/controllers/ChangeEmailController.scala, app/com/gu/identity/frontend/errors/ChangeEmailTokenAppException.scala, app/com/gu/identity/frontend/errors/ErrorID.scala, app/com/gu/identity/frontend/errors/HttpError.scala, app/com/gu/identity/frontend/models/text/ChangeEmailText.scala, app/com/gu/identity/frontend/models/text/ErrorPageText.scala, app/com/gu/identity/frontend/services/IdentityService.scala, app/com/gu/identity/frontend/services/IdentityServiceRequestHandler.scala, app/com/gu/identity/frontend/views/ViewRenderer.scala, app/com/gu/identity/frontend/views/models/ChangeEmailViewModel.scala, app/com/gu/identity/service/client/ApiResponses.scala, app/com/gu/identity/service/client/IdentityClient.scala, app/com/gu/identity/service/client/request/ChangeEmailTokenRequest.scala, conf/DEV.conf, conf/messages.en, conf/routes, public/change-email-page.hbs
Related PR's:
- Identity: https://github.com/guardian/identity/pull/1241
- Frontend : https://github.com/guardian/frontend/pull/19888
- Page for forwarding change email tokens to the API
Success : 
Failure :
=> Change email token page

app/com/gu/identity/frontend/configuration/Configuration.scala, app/com/gu/identity/frontend/models/ReturnUrl.scala, app/com/gu/identity/frontend/models/Text.scala, app/com/gu/identity/frontend/models/text/RegisterText.scala, app/com/gu/identity/frontend/views/models/RegisterViewModel.scala, app/com/gu/identity/frontend/views/models/SignInViewModel.scala, app/com/gu/identity/frontend/views/models/TwoStepSignInChoicesViewModel.scala, conf/application.conf, test/com/gu/identity/frontend/models/ReturnUrlSpec.scala
When people hit identity with the new `recurringContributions` client ID, we want them to:
**a)** See the new header on the `/register` and `/signin/start` flows
**b)** See the "Support the guardian" title with a standfirst saying "Create your Guardian account" on the `/register` page
**c)**  See the custom title and copy on the `/signin/start` flow
**a)** and **c)** were implemented in [this PR](https://github.com/guardian/identity-frontend/pull/425). This PR implements **b)**, and also sets the default returnUrl to `support.theguardian.com` (although the returnUrl should be passed through from support frontend so hopefully this won't be needed, I'm just following the pattern for the `members` clientId)
In the near future we should stop sending the `members` clientId from support …
=> Implement changes for the recurringContributions clientId

app/com/gu/identity/frontend/analytics/client/MeasurementProtocolRequest.scala, app/com/gu/identity/frontend/controllers/SigninAction.scala
Turns out #407 was NOT duplicating data after all (oops) and as such left a gap in our reporting. This PR puts smart lock tracking back up.
=> Re-add smart lock tracking

public/components/ajax-step-flow/ajax-step-flow.js, public/js/load-components.js, public/main.js
Makes `loadComponents` always know its components os you don't have to pass them around, which doesn't provide any real benefit. Prep work for #431
=> Simpler loadComponents signature

conf/messages.en
Uniformly refer to our `Terms & Conditions` as `Terms & Conditions`. Sometimes we would use `Terms of Service` instead. This has been cleared up by legal and it's now T&C's across the board so we are good to go!
=> Update T&C's wording

public/components/ajax-step-flow/ajax-step-flow__slide.js, public/components/smartlock-trigger/smartlock-trigger.js
Small health task:
I've gone through our Sentry sentry errors and 90% of what we send is smartlock errors for browsers that don't support it, so I'm making those fail silently now because there's nothing for us to do (and they aren't actual errors)
There's also a slight improvement for MALFORMED_RESPONSE where we'll log the full response. I expect these to be the server taking too long to respond and thus returning an empty page but it doesn't hurt to know.
=> Clean up sentry reporting

public/components/form/_form.global.css, public/components/jobs/_jobs.global.css, public/components/layout/_layout.global.css, public/components/recurringContributions/_recurringContributions.global.css, public/css/globals/_mixins-type.css, public/css/globals/_vars.css
- [More compact layouts on mobile](https://trello.com/c/oFJj3NZe/778-review-font-sizes-spacing-layout-on-identity-frontend)
- [Bring back the Guardian Jobs branding](https://trello.com/c/mzWb3gNs/807-guardian-jobs-branding-on-identity-screen-for-jobs)
- Avoid header text overlapping the logo on mobile
- Add back the background behind `or` on the divider so it's no longer crossed out
- Sync up horizontal/vertical rhythm with contributions
<table>
<tr><td width="50%">
</td><td width="50%">
</tr></table>
=> CSS alterations

public/components/two-step-signin/two-step-signin-existing.hbs, public/components/two-step-signin/two-step-signin-guest.hbs, public/components/two-step-signin/two-step-signin-new.hbs, public/components/two-step-signin/two-step-signin-start.hbs
This PR adds ids to the submits on the 2 step sign in flow to make selenium testing easier.
(I am currently updating the `support-frontend` selenium tests to work with the new 2 step sign in flow, hence this PR)
=> Add ids to make selenium testing easier

cloudformation/identity-frontend.yaml
Kinesis plugin for logstash appears to bump memory usage, so allowing for that should stop the app crashing.
=> Take logstash into account in memory calculation

public/components/recurringContributions/_recurringContributions.global.css
So sorry! Forgot about adding `&` as part of the CSS migration
=> Fix logo on contributions siteskin

public/components/ajax-step-flow/ajax-step-flow__slide.js, public/components/sentry/sentry.js, public/js/hydrate-react-island.js, public/js/load-components.js, public/main.js
- Load Sentry's SDK as an async chunk, meaning our initial js is quicker to load
- Report exceptions properly
- Report ajax load errors as context instead of as very long text
=> Sentry js improvements

cloudformation/identity-frontend.yaml
uses the new ACM profile.theguardian.com ssl certificate
=> use non beta ssl certificate for identity frontend

cloudformation/identity-frontend.yaml
remove http from loadbalancer
- This was added while changing the ssl certificate, it is no longer needed
=> remove http from loadbalancer

conf/messages.en
Super tiny update to sync up our titles with gu.com
=> Remove "| Identity" from page titles

app/com/gu/identity/frontend/services/IdentityServiceRequestHandler.scala
- Frontend couldn't handle the different types of timestamp we occasionally send it (datetime with milliseconds and without)
=> Handle all timestamps

public/components/form/_form-checkbox.global.css, public/components/two-step-signin/two-step-signin-new.hbs
- Make the checkbox copy slightly larger
- Replace the social sign up buttons on this stage with a "back to options" navigation link
=> UX + A11y updates to register page

public/components/register-form/_form-field-consent.hbs
Added functionality to recently added jobs consent checkbox on registration page to enable tracking via Ophan and GA
=> Add data-link-name for jobs checkbox tracking

app/com/gu/identity/frontend/models/ReturnUrl.scala
On jobs login, there was no default return URL set so users were being returned to theguardian.com.
=> add jobs default url redirect

app/com/gu/identity/service/client/Errors.scala
- Return a Bad request error if request is wrong e.g consent token is expired
- Return an unauthorised if client is unauthorised e.g users cookie is invalid
Fixes issue of expired consent tokens not being redirected to resend link page.
=> Differentiate bad request and unauthorised

app/com/gu/identity/frontend/controllers/ConsentController.scala, conf/routes
Need to pass return URL when following the consent magic link flow
Relevant IDAPI change : https://github.com/guardian/identity/pull/1427/files#diff-efb0c32dce7e8337c306d05648974000L8
=> Return url in consent Controller

app/com/gu/identity/frontend/authentication/CookieService.scala, app/com/gu/identity/frontend/controllers/Application.scala, app/com/gu/identity/frontend/controllers/SigninAction.scala
Since we are only using the cookie in the next request, this seems like a perfect use case for [ScalaSessionFlash](https://www.playframework.com/documentation/2.6.x/ScalaSessionFlash). This solves the problem of the `GU_SIGNIN_EMAIL` cookie lasting for a whole session, which potentially lead to confusing behaviour for the user.
I also took the time to refactor the action `emailSignInFirstStep` - motivation included in the comments.
=> Replace GU_SIGNIN_EMAIL with value in Session Flash

app/com/gu/identity/frontend/controllers/Application.scala
For use by support frontend. They want to bypass the first stage since they know the user's email address and their user type (current).
Thinking about it, I can't see why passing through email as a query string couldn't work for all cases, but I'll leave that for a another potential PR.
=> Look for email in query string if not in flash

app/com/gu/identity/frontend/models/ClientID.scala, public/components/simple-and-coherent/_simple-and-coherent.global.css, public/js/load-global-css.js
When designs come through, CSS can go in _simple-and-coherent.global.css. Variations to sign in page use layout specified in two-step-signin-start-page.hbs and text is mapped in Text.scala.
=> Setup for S&C sign-in page

app/com/gu/identity/frontend/authentication/AuthenticationService.scala, app/com/gu/identity/frontend/authentication/CookieName.scala, app/com/gu/identity/frontend/controllers/SigninAction.scala, test/com/gu/identity/frontend/controllers/SignOutActionSpec.scala, test/com/gu/identity/frontend/controllers/SigninActionSpec.scala
- Remove GU_SIGNIN_EMAIL cookie after successful login
- Remove GU_SIGNIN_EMAIL on successful logout
- Also start to remove SC_GU_LA on logout (should have been doing this anyway)
NB:
Decided to leave the signin_email as a session cookie, this way it will still be around if the user navigates away from profile then back to it later. I don't think it is necessary to enforce it's deletion after a certain time.
=> Remove signin email on login and logout
